#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-tilt
Version  : 2.0.2
Release  : 7
URL      : https://rubygems.org/downloads/tilt-2.0.2.gem
Source0  : https://rubygems.org/downloads/tilt-2.0.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-tilt-bin
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-haml
BuildRequires : rubygem-rdoc

%description
Tilt [![Build Status](https://secure.travis-ci.org/rtomayko/tilt.svg)](http://travis-ci.org/rtomayko/tilt) [![Dependency Status](https://gemnasium.com/rtomayko/tilt.png)](https://gemnasium.com/rtomayko/tilt) [![Inline docs](http://inch-ci.org/github/rtomayko/tilt.png)](http://inch-ci.org/github/rtomayko/tilt)
====

%package bin
Summary: bin components for the rubygem-tilt package.
Group: Binaries

%description bin
bin components for the rubygem-tilt package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n tilt-2.0.2
gem spec %{SOURCE0} -l --ruby > rubygem-tilt.gemspec

%build
gem build rubygem-tilt.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
tilt-2.0.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/tilt-2.0.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/HACKING
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/bin/tilt
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/docs/TEMPLATES.md
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/docs/common.css
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/asciidoc.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/babel.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/bluecloth.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/coffee.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/creole.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/csv.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/erb.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/erubis.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/etanni.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/haml.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/kramdown.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/less.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/liquid.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/mapping.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/markaby.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/maruku.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/nokogiri.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/plain.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/prawn.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/radius.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/rdiscount.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/rdoc.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/redcarpet.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/redcloth.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/sass.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/template.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/wikicloth.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/yajl.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/man/index.txt
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/man/tilt.1.ronn
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/markaby/locals.mab
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/markaby/markaby.mab
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/markaby/markaby_other_static.mab
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/markaby/render_twice.mab
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/markaby/scope.mab
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/markaby/yielding.mab
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_asciidoctor_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_babeltemplate.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_blueclothtemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_buildertemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_cache_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_coffeescripttemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_compilesite_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_creoletemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_csv_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_erbtemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_erubistemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_etannitemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_hamltemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_kramdown_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_lesstemplate_test.less
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_lesstemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_liquidtemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_mapping_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_markaby_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_markdown_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_marukutemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_metadata_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_nokogiritemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_prawntemplate.prawn
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_prawntemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_radiustemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_rdiscounttemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_rdoctemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_redcarpettemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_redclothtemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_sasstemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_stringtemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_template_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_wikiclothtemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/test/tilt_yajltemplate_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/tilt-2.0.2/tilt.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/tilt-2.0.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/tilt
